version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: /app

    steps:
      - checkout

      # Installez les dépendances du projet
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Exécutez les tests
      - run:
          name: Run tests
          command: |
            python -m pytest

workflows:
  version: 2
  build:
    jobs:
      - build
